version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: blastd
    main: .
    binary: blastd
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: "386"

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: taigrr
    name: blastd
  draft: false
  prerelease: auto

nfpms:
  - id: packages
    package_name: blastd
    vendor: Tai Groot
    homepage: https://github.com/taigrr/blastd
    maintainer: Tai Groot <groot.tai@gmail.com>
    description: Local daemon for Blast activity tracking
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
